# Generated by Django 3.2.3 on 2021-06-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ad')),
                ('content', models.TextField(verbose_name='Haqqında')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
