# Generated by Django 3.2.3 on 2021-06-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Haqqında')),
            ],
        ),
        migrations.CreateModel(
            name='Sosial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ad')),
                ('klass', models.CharField(max_length=50, verbose_name='klass')),
            ],
        ),
    ]
