# Generated by Django 3.2.3 on 2021-06-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_about_sosial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Şəkil'),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Şəkil'),
        ),
    ]
